# docker-compose build && docker-compose up

version: "3"

networks:
  datatools:
  
volumes:
  datatools_postgis:
  datatools_postgis_dbbackups:

services:
  datatools-ui:
    container_name: datatools-ui
    build:
      context: ./datatools-ui/
    environment:
      - MAPZEN_TURN_BY_TURN_KEY=${MAPZEN_TURN_BY_TURN_KEY}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - TRANSITFEEDS_API_KEY=${TRANSITFEEDS_API_KEY}
    networks:
      - datatools
    links:
      - datatools-server
    depends_on:
      - datatools-server
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      
  datatools-server:
    container_name: datatools-server
    build: ./datatools-server/
    environment:
      - MONGO_DATA_DIR=/data/db
      - AUTH0_TOKEN=${AUTH0_TOKEN}
      - AUTH0_PUBLIC_KEY=${AUTH0_PUBLIC_KEY}
      - TRANSITFEEDS_API_KEY=${TRANSITFEEDS_API_KEY}
    networks:
      - datatools
    links:
      - datatools-mongodb:mongo
      - datatools-postgis:postgis
    depends_on:
      - datatools-mongodb
      - datatools-postgis
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"

  datatools-mongodb:
    container_name: datatools-mongodb
    image: mongo:latest
    networks:
      - datatools
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0 -v --dbpath /data/db --nojournal --oplogSize 16 --noauth
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      
  datatools-nginx:
    restart: always
    container_name: datatools-nginx
    build: ./nginx/
    networks:
      - datatools
    links:
      - datatools-server
      - datatools-ui
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "9081:9081"

  datatools-postgis:
    container_name: datatools-postgis
    image: kartoza/postgis:9.6-2.4
    volumes:
      - datatools_postgis:/var/lib/postgresql
      - datatools_postgis_dbbackups:/backups
    environment:
      - POSTGRES_DB=gtfs_storage_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    networks:
      - napote  